# Test values to limit the load during CI
kubeVersionOverride: "1.20"

configStorageType: Secret

enterprise:
  enabled: true

alertmanager:
  persistentVolume:
    enabled: false

compactor:
  persistentVolume:
    enabled: false

ingester:
  persistentVolume:
    enabled: false
  resources:
    requests:
      cpu: 10m
  podDisruptionBudget:
    maxUnavailable: 1

store_gateway:
  persistentVolume:
    enabled: false
